name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
        override: true
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: Lint
      run: cargo clippy --all-features -- --deny warnings
    - name: Check Style
      run: cargo fmt -- --check
